mysite/urls.py
from django.contrib import admin
from django.urls import path, include

### admin1
#from predict.admin import

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls', namespace='predict')),
]

predict/urls.py
from django.urls import path
from . import views

from django.contrib import admin

app_name = 'predict'


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),

    path('import_dataset/', views.import_dataset, name="import_dataset"),
    path('import_csv/', views.import_csv, name="import_csv"),

    path('datasets/', views.datasets, name="datasets"),
    path('approval/', views.approval, name="approval"),

    path('args2/', views.args2, name='args2'),
    path('args2_chances/', views.args2_chances, name='args2_chances'),
    path('args3/', views.args3, name='args3'),
    path('args3_chances/', views.args3_chances, name='args3_chances'),
    path('args4/', views.args4, name='args4'),
    path('args4_chances/', views.args4_chances, name='args4_chances'),
    path('args5/', views.args5, name='args5'),
    path('args5_chances/', views.args5_chances, name='args5_chances'),
    path('args6/', views.args6, name='args6'),
    path('args6_chances/', views.args6_chances, name='args6_chances'),
    path('args7/', views.args7, name='args7'),
    path('args7_chances/', views.args7_chances, name='args7_chances'),
    path('args8/', views.args8, name='args8'),
    path('args8_chances/', views.args8_chances, name='args8_chances'),
    path('args9/', views.args9, name='args9'),
    path('args9_chances/', views.args9_chances, name='args9_chances'),

    path('database_list/', views.database_list, name="database_list"),
    
]

templates/num_args/args2.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->
<div class="modal fade colorblack" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rezultat</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Data entered:</h5>
                <div>{{data.a1}}: <span id="aa1"></span></div>
                <div>{{data.a1}}: <span id="aa2"></span></div>

                <h5 class="pt-3">Result:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                
            </div>

        </div>
    </div>
</div>


<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            Loaded dataset:

            <b>{{data.model_name}}</b> </br>
            <h3>Enter data:</h3> </br>
            
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="a1">{{data.a1}}</label>
                    <input type="number" step="0.1" class="form-control" id="a1" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a2">{{data.a2}}</label>
                    <input type="number" step="0.1" class="form-control" id="a2" placeholder="" required>
                </div>


                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >Submit</button>
                <button type="reset" value="Clear" class="btn btn-primary">Clear</button>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:args2_chances" %}',
            data:{
                a1:$('#a1').val(),
                a2:$('#a2').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"];
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("aa1").innerHTML = json['a1']
                document.getElementById("aa2").innerHTML = json['a2']

            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

templates/num_args/args3.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->
<div class="modal fade colorblack" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rezultat</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Data entered:</h5>
                <div>{{data.a1}}: <span id="aa1"></span></div>
                <div>{{data.a2}}: <span id="aa2"></span></div>
                <div>{{data.a3}}: <span id="aa3"></span></div>

                <h5 class="pt-3">Result:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                
            </div>

        </div>
    </div>
</div>




<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            Loaded dataset:

            <b>{{data.model_name}}</b> </br>
            <h3>Enter data:</h3> </br>
            
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="a1">{{data.a1}}</label>
                    <input type="number" step="0.1" class="form-control" id="a1" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a2">{{data.a2}}</label>
                    <input type="number" step="0.1" class="form-control" id="a2" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a3">{{data.a3}}</label>
                    <input type="number" step="0.1" class="form-control" id="a3" placeholder="" required>
                </div>

                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >Submit</button>
                <button type="reset" value="Clear" class="btn btn-primary">Clear</button>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:args3_chances" %}',
            data:{
                a1:$('#a1').val(),
                a2:$('#a2').val(),
                a3:$('#a3').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"];
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("aa1").innerHTML = json['a1']
                document.getElementById("aa2").innerHTML = json['a2']
                document.getElementById("aa3").innerHTML = json['a3']

            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


{% endblock %}

templates/num_args/args4.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->
<div class="modal fade colorblack" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Result</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Data entered:</h5>
                <div>{{data.a1}}: <span id="aa1"></span></div>
                <div>{{data.a2}}: <span id="aa2"></span></div>
                <div>{{data.a3}}: <span id="aa3"></span></div>
                <div>{{data.a4}}: <span id="aa4"></span></div>

                <h5 class="pt-3">Result:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                
            </div>

        </div>
    </div>
</div>




<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            Loaded dataset:

            <b>{{data.model_name}}</b> </br>
            <h3>Enter data:</h3> </br>
            
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="a1">{{data.a1}}</label>
                    <input type="number" step="0.1" class="form-control" id="a1" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a2">{{data.a2}}</label>
                    <input type="number" step="0.1" class="form-control" id="a2" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a3">{{data.a3}}</label>
                    <input type="number" step="0.1" class="form-control" id="a3" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a4">{{data.a4}}</label>
                    <input type="number" step="0.1" class="form-control" id="a4" placeholder="" required>
                </div>

                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button> </br>
                <button type="reset" value="Clear" class="btn btn-primary">Clear</button>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:args4_chances" %}',
            data:{
                a1:$('#a1').val(),
                a2:$('#a2').val(),
                a3:$('#a3').val(),
                a4:$('#a4').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"];
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("aa1").innerHTML = json['a1']
                document.getElementById("aa2").innerHTML = json['a2']
                document.getElementById("aa3").innerHTML = json['a3']
                document.getElementById("aa4").innerHTML = json['a4']

            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


{% endblock %}

templates/num_args/args5.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->
<div class="modal fade colorblack" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rezultat</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Data entered:</h5>
                <div>{{data.a1}}: <span id="aa1"></span></div>
                <div>{{data.a2}}: <span id="aa2"></span></div>
                <div>{{data.a3}}: <span id="aa3"></span></div>
                <div>{{data.a4}}: <span id="aa4"></span></div>
                <div>{{data.a5}}: <span id="aa5"></span></div>

                <h5 class="pt-3">Result:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                
            </div>

        </div>
    </div>
</div>




<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            Loaded dataset:

            <b>{{data.model_name}}</b> </br>
            <h3>Enter data:</h3> </br>
            
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="a1">{{data.a1}}</label>
                    <input type="number" step="0.1" class="form-control" id="a1" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a2">{{data.a2}}</label>
                    <input type="number" step="0.1" class="form-control" id="a2" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a3">{{data.a3}}</label>
                    <input type="number" step="0.1" class="form-control" id="a3" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a4">{{data.a4}}</label>
                    <input type="number" step="0.1" class="form-control" id="a4" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a5">{{data.a5}}</label>
                    <input type="number" step="0.1" class="form-control" id="a5" placeholder="" required>
                </div>

                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >Submit</button>
                <button type="reset" value="Clear" class="btn btn-primary">Clear</button>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:args5_chances" %}',
            data:{
                a1:$('#a1').val(),
                a2:$('#a2').val(),
                a3:$('#a3').val(),
                a4:$('#a4').val(),
                a5:$('#a5').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"];
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("aa1").innerHTML = json['a1']
                document.getElementById("aa2").innerHTML = json['a2']
                document.getElementById("aa3").innerHTML = json['a3']
                document.getElementById("aa4").innerHTML = json['a4']
                document.getElementById("aa5").innerHTML = json['a5']

            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


{% endblock %}

templates/num_args/args6.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->
<div class="modal fade colorblack" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rezultat</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Data entered:</h5>
                <div>{{data.a1}}: <span id="aa1"></span></div>
                <div>{{data.a2}}: <span id="aa2"></span></div>
                <div>{{data.a3}}: <span id="aa3"></span></div>
                <div>{{data.a4}}: <span id="aa4"></span></div>
                <div>{{data.a5}}: <span id="aa5"></span></div>
                <div>{{data.a6}}: <span id="aa6"></span></div>

                <h5 class="pt-3">Result:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                
            </div>

        </div>
    </div>
</div>




<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            Loaded dataset:

            <b>{{data.model_name}}</b> </br>
            <h3>Enter data:</h3> </br>
            
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="a1">{{data.a1}}</label>
                    <input type="number" step="0.1" class="form-control" id="a1" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a2">{{data.a2}}</label>
                    <input type="number" step="0.1" class="form-control" id="a2" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a3">{{data.a3}}</label>
                    <input type="number" step="0.1" class="form-control" id="a3" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a4">{{data.a4}}</label>
                    <input type="number" step="0.1" class="form-control" id="a4" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a5">{{data.a5}}</label>
                    <input type="number" step="0.1" class="form-control" id="a5" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a6">{{data.a6}}</label>
                    <input type="number" step="0.1" class="form-control" id="a6" placeholder="" required>
                </div>

                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >Submit</button>
                <button type="reset" value="Clear" class="btn btn-primary">Clear</button>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:args6_chances" %}',
            data:{
                a1:$('#a1').val(),
                a2:$('#a2').val(),
                a3:$('#a3').val(),
                a4:$('#a4').val(),
                a5:$('#a5').val(),
                a6:$('#a6').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"];
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("aa1").innerHTML = json['a1']
                document.getElementById("aa2").innerHTML = json['a2']
                document.getElementById("aa3").innerHTML = json['a3']
                document.getElementById("aa4").innerHTML = json['a4']
                document.getElementById("aa5").innerHTML = json['a5']
                document.getElementById("aa6").innerHTML = json['a6']

            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


{% endblock %}

templates/num_args/args7.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->
<div class="modal fade colorblack" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rezultat</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Data entered:</h5>
                <div>{{data.a1}}: <span id="aa1"></span></div>
                <div>{{data.a2}}: <span id="aa2"></span></div>
                <div>{{data.a3}}: <span id="aa3"></span></div>
                <div>{{data.a4}}: <span id="aa4"></span></div>
                <div>{{data.a5}}: <span id="aa5"></span></div>
                <div>{{data.a6}}: <span id="aa6"></span></div>
                <div>{{data.a7}}: <span id="aa7"></span></div>

                <h5 class="pt-3">Result:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                
                
            </div>

        </div>
    </div>
</div>




<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            Loaded dataset:

            <b>{{data.model_name}}</b> </br>
            <h3>Enter data:</h3> </br>
            
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="a1">{{data.a1}}</label>
                    <input type="number" step="0.1" class="form-control" id="a1" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a2">{{data.a2}}</label>
                    <input type="number" step="0.1" class="form-control" id="a2" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a3">{{data.a3}}</label>
                    <input type="number" step="0.1" class="form-control" id="a3" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a4">{{data.a4}}</label>
                    <input type="number" step="0.1" class="form-control" id="a4" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a5">{{data.a5}}</label>
                    <input type="number" step="0.1" class="form-control" id="a5" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a6">{{data.a6}}</label>
                    <input type="number" step="0.1" class="form-control" id="a6" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a7">{{data.a7}}</label>
                    <input type="number" step="0.1" class="form-control" id="a7" placeholder="" required>
                </div>


                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >Submit</button>
                <button type="reset" value="Clear" class="btn btn-primary">Clear</button>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:args7_chances" %}',
            data:{
                a1:$('#a1').val(),
                a2:$('#a2').val(),
                a3:$('#a3').val(),
                a4:$('#a4').val(),
                a5:$('#a5').val(),
                a6:$('#a6').val(),
                a7:$('#a7').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"];
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("aa1").innerHTML = json['a1']
                document.getElementById("aa2").innerHTML = json['a2']
                document.getElementById("aa3").innerHTML = json['a3']
                document.getElementById("aa4").innerHTML = json['a4']
                document.getElementById("aa5").innerHTML = json['a5']
                document.getElementById("aa6").innerHTML = json['a6']
                document.getElementById("aa7").innerHTML = json['a7']

            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


{% endblock %}

templates/num_args/args8.html
{% extends "base.html" %}

{% block main %}

<!-- Modal -->
<div class="modal fade colorblack" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rezultat</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Data entered:</h5>
                <div>{{data.a1}}: <span id="aa1"></span></div>
                <div>{{data.a2}}: <span id="aa2"></span></div>
                <div>{{data.a3}}: <span id="aa3"></span></div>
                <div>{{data.a4}}: <span id="aa4"></span></div>
                <div>{{data.a5}}: <span id="aa5"></span></div>
                <div>{{data.a6}}: <span id="aa6"></span></div>
                <div>{{data.a7}}: <span id="aa7"></span></div>
                <div>{{data.a8}}: <span id="aa8"></span></div>

                <h5 class="pt-3">Result</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                
            </div>

        </div>
    </div>
</div>




<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            Loaded dataset:

            <b>{{data.model_name}}</b> </br>
            <h3>Enter data:</h3> </br>
            
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="a1">{{data.a1}}</label>
                    <input type="number" step="0.1" class="form-control" id="a1" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a2">{{data.a2}}</label>
                    <input type="number" step="0.1" class="form-control" id="a2" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a3">{{data.a3}}</label>
                    <input type="number" step="0.1" class="form-control" id="a3" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a4">{{data.a4}}</label>
                    <input type="number" step="0.1" class="form-control" id="a4" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a5">{{data.a5}}</label>
                    <input type="number" step="0.1" class="form-control" id="a5" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a6">{{data.a6}}</label>
                    <input type="number" step="0.1" class="form-control" id="a6" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a7">{{data.a7}}</label>
                    <input type="number" step="0.1" class="form-control" id="a7" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="a8">{{data.a8}}</label>
                    <input type="number" step="0.1" class="form-control" id="a8" placeholder="" required>
                </div>


                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >Submit</button>
                <button type="reset" value="Clear" class="btn btn-primary">Clear</button>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:args8_chances" %}',
            data:{
                a1:$('#a1').val(),
                a2:$('#a2').val(),
                a3:$('#a3').val(),
                a4:$('#a4').val(),
                a5:$('#a5').val(),
                a6:$('#a6').val(),
                a7:$('#a7').val(),
                a8:$('#a8').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"];
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("aa1").innerHTML = json['a1']
                document.getElementById("aa2").innerHTML = json['a2']
                document.getElementById("aa3").innerHTML = json['a3']
                document.getElementById("aa4").innerHTML = json['a4']
                document.getElementById("aa5").innerHTML = json['a5']
                document.getElementById("aa6").innerHTML = json['a6']
                document.getElementById("aa7").innerHTML = json['a7']
                document.getElementById("aa8").innerHTML = json['a8']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


{% endblock %}